In [228]:
import pandas as pd

In [229]:
df = pd.read_csv("pokemon.csv")

In [230]:
df ['name_lower'] = df ['name'].str.lower()

In [231]:
df.head()

   id        name  type1   type2  hp  attack  defense  speed  name_lower
0   1   Bulbasaur  Grass  Poison  45      49       49     45   bulbasaur
1   2     Ivysaur  Grass  Poison  60      62       63     60     ivysaur
2   3    Venusaur  Grass  Poison  80      82       83     80    venusaur
3   4  Charmander   Fire     NaN  39      52       43     65  charmander
4   5  Charmeleon   Fire     NaN  58      64       58     80  charmeleon

In [232]:
df['name_upper'] = df ['name'].str.upper()

In [233]:
df.head()

,id,name,type1,type2,hp,attack,defense,speed,name_lower,name_upper
0,1,Bulbasaur,Grass,Poison,45,49,49,45,bulbasaur,BULBASAUR
1,2,Ivysaur,Grass,Poison,60,62,63,60,ivysaur,IVYSAUR
2,3,Venusaur,Grass,Poison,80,82,83,80,venusaur,VENUSAUR
3,4,Charmander,Fire,NaN,39,52,43,65,charmander,CHARMANDER
4,5,Charmeleon,Fire,NaN,58,64,58,80,charmeleon,CHARMELEON

In [234]:
'apple eat' .strip()

'apple eat'

In [235]:
df['type1'].str.strip().str.upper()

0    GRASS
1    GRASS
2    GRASS
3     FIRE
4     FIRE
5     FIRE
6    WATER
7    WATER
8    WATER
Name: type1, dtype: str

In [236]:
df['attack'].mean()

np.float64(65.22222222222223)

In [237]:
df ['attack'].sum()

np.int64(587)

In [238]:
df['attack'].median()

np.float64(63.0)

In [239]:
df.groupby(by = ['type1']).agg({
    "attack" : ["mean", "sum" , "min" , "max"],
    "hp" : "sum"
}).reset_index()

   type1     attack                hp
               mean  sum min max  sum
0   Fire  66.666667  200  52  84  175
1  Grass  64.333333  193  49  82  185
2  Water  64.666667  194  48  83  182

In [240]:
mew_df = df.groupby(by = ['type1']).agg(
  attack_min = pd.NamedAgg(column= "attack",aggfunc = "min"),
  attack_max = pd.NamedAgg(column = "attack" , aggfunc = "max"),
  attack_avg = pd.NamedAgg(column = "attack" , aggfunc= "mean")
).reset_index()

In [241]:
mew_df.to_csv("new data.csv" , index = False)